select TASKDETAILKEY,LOT,FROMLOC,TOLOC,FROMID,TOID,qty,sourcekey FROM WMWHSE1.TASKDETAIL TD
WHERE EXISTS( SELECT 1 FROM WMWHSE1.ITRN WHERE LOT = TD.LOT AND FROMLOC=TD.FROMLOC
AND SOURCEKEY = TD.SOURCEKEY AND FROMID = TD.FROMID AND TRANTYPE='MV')
AND STATUS <'9' AND TASKTYPE ='PA' 


